source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

gem 'turbolinks'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'execjs'

# localhost以外からもエラー時にコンソールが打てる
# rails s TRUSTED_IP=xxx.xxx.xxx.xxx
group :development do
  gem "better_errors"
end

gem 'steam-condenser', '1.3.8.1'

# テンプレートエンジンを haml に変更
gem 'haml-rails'

